### ISSUE TITLE
Program showing error while launching chromeDriver using selenium.

### ISSUE THREAD

**Issue by RoseRaju** [LiuYuancheng/Windows_User_Simulator#1]
Observed the following error, while the program launched chrome for watching Youtube video or joining zoom meeting : "Unable to obtain driver for chrome using Selenium Manager":

**Comment by LiuYuancheng** [comment]
Many thanks for submit the issue and supply the solution, the effected file
1. dinoactor.py
2. funcActor.py
3. functionActors.py
4. zoomActor.py
Are fixed based on the solution you provide (https://pypi.org/project/webdriver-manager/) in the patch commit **657df87**
